### PR TITLE
Draft features

### PR DESCRIPTION
**Pull request by Gnwin**
We implemented in this project a clone for the youtube video player and we are waiting for your review.

### CODE REVIEW

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Status: Changes required 🚨

## Impressive project @Gnwin 👏🙌

### But we need to work on some changes.

Before I list the changes, we need to be clear on some things.

- This is supposed to be a collaborative project but I only see your (@Gnwin) commits. The previous reviewer had asked for an explanation but I am not seeing any. So make sure that you provide the info if you are authorized to make a collaborative project alone.
- I see that you are creating new PRs for each code review. It's a bad practice because the context is lost and it sometimes confuses the reviewers. From the next time remember to use the same PR for all code reviews.

The changes:

- The `video-summary` section needs to be exactly like the original. This was also pointed out by the previous TSE.

Right now 👇
Annotation 2020-06-16 233354

Original 👇
Annotation 2020-06-16 233335

- Reduce the image sizes in this section 👇
Annotation 2020-06-16 234750


Make sure that you apply these changes **BEFORE** submitting another code review.

Happy coding 👨‍💻

**Comment by Gnwin** [comment]
Comment 1:
This is supposed to be a collaborative project but I only see your (@Gnwin) commits. The previous reviewer had asked for an explanation but I am not seeing any. So make sure that you provide the info if you are authorized to make a collaborative project alone.

Answer 1:
Yes, this is supposed to be a collaborative project. I and my partner made commits in the first draft of our project which we mistakenly merged before we made our first pull request. we were then told to transfer all project files into a new repo and I (@Gnwin) took the agreed responsibility of doing that and we worked together to fix it but I just committed and pushed even though we worked together as there was only small changes involved. That's exactly why it seems I am the only one making commits. Also, I have explained it to our previous TSE about this very well and he just told us to brief here about the same. Going forward, we will be deliberate about distributing feature commits and I hope that this clears the misunderstanding caused.




Recommended change:
The video-summary section needs to be exactly like the original. This was also pointed out by the previous TSE.

Comment:
we were told to clone this mockup:  http://archive.today/Bss88     
And not the live youtube page.

**Comment by tirthajyoti-ghosh** [comment]
Hello @Gnwin!
Thank you for clearing that up.

I've just realized that cloning the actual youtube page is not required in this project. In that case, you and your partner have done a fantastic job 👏.

I am sorry to mislead you. I haven't done that on purpose :blush:.

Best of luck for the next projects.

**Review by tirthajyoti-ghosh — APPROVED** [review]
# Status: Approved ✔

## Nice job team 🙌👏. It's a 👍 from me.

### Go ahead and merge it. Onto the next project 🚀.

Happy coding 👨‍💻

**Pull request merged**
